FROM ubuntu:24.04

RUN apt-get update && apt-get install -y \
  openssh-server \
  iputils-ping \
  curl \
  python3 \
  python3-apt && \
  mkdir /var/run/sshd

# ポートかえる
RUN sed -i 's/#Port 22/Port 2222/' /etc/ssh/sshd_config

RUN echo 'root:root' | chpasswd

RUN sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config

EXPOSE 2222

CMD ["/usr/sbin/sshd", "-D"]
